/**
 * This file contains the complete list of all 75+ animation components
 * to be added to the component registry.
 *
 * Copy these entries into component-registry.ts
 */

export const additionalAnimationComponents = [
  // Text Animations (Advanced)
  {
    slug: "pixel-ascii-text",
    title: "ASCII Text",
    description: "Convert text to ASCII art with animation effects.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelASCIIText } from "@/components/ui/pixel/animations/pixel-ascii-text"`,
    usageCode: `<PixelASCIIText text="PIXEL" />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-ascii-text.tsx`,
  },
  {
    slug: "pixel-split-text",
    title: "Split Text",
    description: "Text animation with split and stagger effects.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelSplitText } from "@/components/ui/pixel/animations/pixel-split-text"`,
    usageCode: `<PixelSplitText text="SPLIT" splitType="chars" />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-split-text.tsx`,
  },
  {
    slug: "pixel-rotating-text",
    title: "Rotating Text",
    description: "Text that rotates through multiple words or phrases.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelRotatingText } from "@/components/ui/pixel/animations/pixel-rotating-text"`,
    usageCode: `<PixelRotatingText words={["Fast", "Simple", "Pixel"]} />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-rotating-text.tsx`,
  },
  {
    slug: "pixel-letter-glitch",
    title: "Letter Glitch",
    description: "Individual letter glitch effect with random characters.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelLetterGlitch } from "@/components/ui/pixel/animations/pixel-letter-glitch"`,
    usageCode: `<PixelLetterGlitch />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-letter-glitch.tsx`,
  },
  {
    slug: "pixel-shuffle-text",
    title: "Shuffle Text",
    description: "Text shuffle animation with scramble effect.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelShuffleText } from "@/components/ui/pixel/animations/pixel-shuffle-text"`,
    usageCode: `<PixelShuffleText text="SHUFFLE" />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-shuffle-text.tsx`,
  },
  {
    slug: "pixel-text-pressure",
    title: "Text Pressure",
    description: "Text that responds to mouse pressure with variable font.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelTextPressure } from "@/components/ui/pixel/animations/pixel-text-pressure"`,
    usageCode: `<PixelTextPressure text="PRESS" />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-text-pressure.tsx`,
  },
  {
    slug: "pixel-true-focus",
    title: "True Focus",
    description: "Text with focus animation highlighting one word at a time.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelTrueFocus } from "@/components/ui/pixel/animations/pixel-true-focus"`,
    usageCode: `<PixelTrueFocus sentence="True Focus" />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-true-focus.tsx`,
  },

  // Card Effects (Advanced)
  {
    slug: "pixel-tilted-card",
    title: "Tilted Card",
    description: "3D tilting card effect that follows mouse movement.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelTiltedCard } from "@/components/ui/pixel/animations/pixel-tilted-card"`,
    usageCode: `<PixelTiltedCard imageSrc="/image.jpg" />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-tilted-card.tsx`,
  },
  {
    slug: "pixel-decay-card",
    title: "Decay Card",
    description: "Card with decay/disintegration effect on hover.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelDecayCard } from "@/components/ui/pixel/animations/pixel-decay-card"`,
    usageCode: `<PixelDecayCard image="/image.jpg" />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-decay-card.tsx`,
  },
  {
    slug: "pixel-sticker-peel",
    title: "Sticker Peel",
    description: "Draggable sticker with peel-back effect.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelStickerPeel } from "@/components/ui/pixel/animations/pixel-sticker-peel"`,
    usageCode: `<PixelStickerPeel imageSrc="/sticker.png" />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-sticker-peel.tsx`,
  },
  {
    slug: "pixel-bounce-cards",
    title: "Bounce Cards",
    description: "Cards with bouncy hover animations.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelBounceCards } from "@/components/ui/pixel/animations/pixel-bounce-cards"`,
    usageCode: `<PixelBounceCards />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-bounce-cards.tsx`,
  },

  // Background Effects
  {
    slug: "pixel-dot-grid",
    title: "Dot Grid",
    description: "Interactive dot grid background with mouse effects.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelDotGrid } from "@/components/ui/pixel/animations/pixel-dot-grid"`,
    usageCode: `<PixelDotGrid />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-dot-grid.tsx`,
  },
  {
    slug: "pixel-squares",
    title: "Squares",
    description: "Animated square grid background.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelSquares } from "@/components/ui/pixel/animations/pixel-squares"`,
    usageCode: `<PixelSquares />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-squares.tsx`,
  },
  {
    slug: "pixel-waves",
    title: "Waves",
    description: "Wave animation background with mouse interaction.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelWaves } from "@/components/ui/pixel/animations/pixel-waves"`,
    usageCode: `<PixelWaves />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-waves.tsx`,
  },
  {
    slug: "pixel-ribbons",
    title: "Ribbons",
    description: "Flowing ribbon effects following the cursor.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelRibbons } from "@/components/ui/pixel/animations/pixel-ribbons"`,
    usageCode: `<PixelRibbons />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-ribbons.tsx`,
  },
  {
    slug: "pixel-meta-balls",
    title: "Meta Balls",
    description: "Liquid meta balls effect with blob interactions.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelMetaBalls } from "@/components/ui/pixel/animations/pixel-meta-balls"`,
    usageCode: `<PixelMetaBalls />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-meta-balls.tsx`,
  },
  {
    slug: "pixel-plasma",
    title: "Plasma",
    description: "Animated plasma background effect.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelPlasma } from "@/components/ui/pixel/animations/pixel-plasma"`,
    usageCode: `<PixelPlasma />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-plasma.tsx`,
  },
  {
    slug: "pixel-grid-motion",
    title: "Grid Motion",
    description: "Grid with motion effects based on mouse position.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelGridMotion } from "@/components/ui/pixel/animations/pixel-grid-motion"`,
    usageCode: `<PixelGridMotion />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-grid-motion.tsx`,
  },
  {
    slug: "pixel-aurora",
    title: "Aurora",
    description: "Aurora borealis background effect.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelAurora } from "@/components/ui/pixel/animations/pixel-aurora"`,
    usageCode: `<PixelAurora />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-aurora.tsx`,
  },
  {
    slug: "pixel-galaxy",
    title: "Galaxy",
    description: "Animated galaxy/space background.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelGalaxy } from "@/components/ui/pixel/animations/pixel-galaxy"`,
    usageCode: `<PixelGalaxy />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-galaxy.tsx`,
  },
  {
    slug: "pixel-ripple-grid",
    title: "Ripple Grid",
    description: "Grid with ripple wave effects.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelRippleGrid } from "@/components/ui/pixel/animations/pixel-ripple-grid"`,
    usageCode: `<PixelRippleGrid />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-ripple-grid.tsx`,
  },

  // Cursor Effects
  {
    slug: "pixel-blob-cursor",
    title: "Blob Cursor",
    description: "Blob-shaped cursor effect that follows the mouse.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelBlobCursor } from "@/components/ui/pixel/animations/pixel-blob-cursor"`,
    usageCode: `<PixelBlobCursor />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-blob-cursor.tsx`,
  },
  {
    slug: "pixel-splash-cursor",
    title: "Splash Cursor",
    description: "Fluid splash effect following cursor movement.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelSplashCursor } from "@/components/ui/pixel/animations/pixel-splash-cursor"`,
    usageCode: `<PixelSplashCursor />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-splash-cursor.tsx`,
  },
  {
    slug: "pixel-target-cursor",
    title: "Target Cursor",
    description: "Targeting crosshair cursor effect.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelTargetCursor } from "@/components/ui/pixel/animations/pixel-target-cursor"`,
    usageCode: `<PixelTargetCursor />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-target-cursor.tsx`,
  },
  {
    slug: "pixel-trail",
    title: "Pixel Trail",
    description: "Pixelated trail following the cursor.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelTrail } from "@/components/ui/pixel/animations/pixel-trail"`,
    usageCode: `<PixelTrail />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-trail.tsx`,
  },
  {
    slug: "pixel-image-trail",
    title: "Image Trail",
    description: "Image trail effect following mouse movement.",
    category: "Animations",
    installation: "",
    importCode: `import { PixelImageTrail } from "@/components/ui/pixel/animations/pixel-image-trail"`,
    usageCode: `<PixelImageTrail images={[]} />`,
    componentCode: `/src/components/ui/pixel/animations/pixel-image-trail.tsx`,
  },
];
